TARGET = XS1-L1A-LQ64

APP_NAME = app_l1_otp_programmer

XCC_FLAGS   	= -D G1 -DSPDIF -O2 -g -Wall -lotp_l1

USED_MODULES =


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
